export const AUTH_USER_SET = 'AUTH_USER_SET';
export const AUTH_USER_GET = 'AUTH_USER_GET';
export const AUTH_USER_REMOVE = 'AUTH_USER_REMOVE';
export const AUTH_USER_CLEAR_ERROR = 'AUTH_USER_CLEAR_ERROR';